export enum USER_ROLE_ENUM {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum USER_NAME_ENUM {
  DEFAULT_NAME = 'DEFAULT_NAME',
}

export enum USER_STATUS_ENUM {
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
}
